### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by M0hanRamS** [MohanRamSridhar/PokemonAPI#25]
test

**Comment by MohanRamSridhar** [comment]
Hello @M0hanRamS Thank you for creating a new issue! 🎉 Your issue is currently under review./nIf you would like to assign this issue to yourself, please comment with the word "self" and the issue will be assigned to you.

**Comment by MohanRamSridhar** [comment]
Hey @M0hanRamS ! Just wanted to inform you that the issue has been closed
Would like to see you again.
